output "system_users" {
  description = "System users generated by the core module."
  sensitive   = true
  value       = module.systems.users
}

output "application_users" {
  description = "Manually selected applilcation users generated by each application_database module."
  sensitive   = true
  value = {
    stitch   = module.stitch_db.user
    fivetran = module.fivetran_db.user
    meltano  = module.meltano_db.user
  }
}
