output system_users {
  description = "System users generated by the core module."
  sensitive   = true
  value       = module.core.system_users
}

output application_users {
  description = "Manually selected applilcation users generated by each app_database module."
  sensitive   = true
  value = {
    analytics = module.analytics_db.user
    load      = module.singer_db.user
  }
}
